version: '{build}'
image: Visual Studio 2017
install:
- ps: >-
    $xmlPath = "$env:appveyor_build_folder\PangLib.Wii.ECB\PangLib.Wii.ECB.csproj"

    $xml = [xml](get-content $xmlPath)

    $version = ($xml.Project.PropertyGroup | ? {$_.Version}).Version

    Update-AppveyorBuild -Version "$version-$env:appveyor_build_id"
before_build:
- ps: >-
    cd PangLib.Wii.ECB/

    dotnet restore
only_commits:
  files:
    - PangLib.Wii.ECB/
build:
  project: PangLib.Wii.ECB/PangLib.Wii.ECB.csproj
  verbosity: minimal